import { Match } from './types';

export const INITIAL_MATCHES: Match[] = [
  // --- GRUPO stage ---
  // Jueves, 11 de junio 2026
  { id: 'wc01', homeTeam: 'México', awayTeam: 'Sudáfrica', group: 'Grupo A', dateTime: '2026-06-11T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Ciudad de México' },
  { id: 'wc02', homeTeam: 'República de Corea', awayTeam: 'República Checa', group: 'Grupo A', dateTime: '2026-06-12T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Guadalajara' },
  // Viernes, 12 de junio 2026
  { id: 'wc03', homeTeam: 'Canadá', awayTeam: 'Bosnia y Herzegovina', group: 'Grupo B', dateTime: '2026-06-12T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Toronto' },
  { id: 'wc04', homeTeam: 'Estados Unidos', awayTeam: 'Paraguay', group: 'Grupo D', dateTime: '2026-06-13T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  // Sábado, 13 de junio 2026
  { id: 'wc05', homeTeam: 'Catar', awayTeam: 'Suiza', group: 'Grupo B', dateTime: '2026-06-13T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Bahía de San Francisco' },
  { id: 'wc06', homeTeam: 'Brasil', awayTeam: 'Marruecos', group: 'Grupo C', dateTime: '2026-06-13T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' },
  { id: 'wc07', homeTeam: 'Haití', awayTeam: 'Escocia', group: 'Grupo C', dateTime: '2026-06-14T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Boston' },
  { id: 'wc08', homeTeam: 'Australia', awayTeam: 'Turquía', group: 'Grupo D', dateTime: '2026-06-14T04:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio BC Place Vancouver' },
  // Domingo, 14 de junio 2026
  { id: 'wc09', homeTeam: 'Alemania', awayTeam: 'Curazao', group: 'Grupo E', dateTime: '2026-06-14T17:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Houston' },
  { id: 'wc10', homeTeam: 'Países Bajos', awayTeam: 'Japón', group: 'Grupo F', dateTime: '2026-06-14T20:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },
  { id: 'wc11', homeTeam: 'Costa de Marfil', awayTeam: 'Ecuador', group: 'Grupo E', dateTime: '2026-06-14T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Filadelfia' },
  { id: 'wc12', homeTeam: 'Suecia', awayTeam: 'Túnez', group: 'Grupo F', dateTime: '2026-06-15T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Monterrey' },
  // Lunes, 15 de junio 2026
  { id: 'wc13', homeTeam: 'España', awayTeam: 'Cabo Verde', group: 'Grupo H', dateTime: '2026-06-15T16:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },
  { id: 'wc14', homeTeam: 'Bélgica', awayTeam: 'Egipto', group: 'Grupo G', dateTime: '2026-06-15T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Seattle' },
  { id: 'wc15', homeTeam: 'Arabia Saudí', awayTeam: 'Uruguay', group: 'Grupo H', dateTime: '2026-06-15T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Miami' },
  { id: 'wc16', homeTeam: 'RI de Irán', awayTeam: 'Nueva Zelanda', group: 'Grupo G', dateTime: '2026-06-16T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  // Martes, 16 de junio 2026
  { id: 'wc17', homeTeam: 'Francia', awayTeam: 'Senegal', group: 'Grupo I', dateTime: '2026-06-16T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' },
  { id: 'wc18', homeTeam: 'Irak', awayTeam: 'Noruega', group: 'Grupo I', dateTime: '2026-06-16T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Boston' },
  { id: 'wc19', homeTeam: 'Argentina', awayTeam: 'Argelia', group: 'Grupo J', dateTime: '2026-06-17T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Kansas City' },
  { id: 'wc20', homeTeam: 'Austria', awayTeam: 'Jordania', group: 'Grupo J', dateTime: '2026-06-17T04:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Bahía de San Francisco' },
  // Miércoles, 17 de junio 2026
  { id: 'wc21', homeTeam: 'Portugal', awayTeam: 'RD Congo', group: 'Grupo K', dateTime: '2026-06-17T17:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Houston' },
  { id: 'wc22', homeTeam: 'Inglaterra', awayTeam: 'Croacia', group: 'Grupo L', dateTime: '2026-06-17T20:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },
  { id: 'wc23', homeTeam: 'Ghana', awayTeam: 'Panamá', group: 'Grupo L', dateTime: '2026-06-17T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Toronto' },
  { id: 'wc24', homeTeam: 'Uzbekistán', awayTeam: 'Colombia', group: 'Grupo K', dateTime: '2026-06-18T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Ciudad de México' },
  // Jueves, 18 de junio 2026
  { id: 'wc25', homeTeam: 'República Checa', awayTeam: 'Sudáfrica', group: 'Grupo A', dateTime: '2026-06-18T16:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },
  { id: 'wc26', homeTeam: 'Suiza', awayTeam: 'Bosnia y Herzegovina', group: 'Grupo B', dateTime: '2026-06-18T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  { id: 'wc27', homeTeam: 'Canadá', awayTeam: 'Catar', group: 'Grupo B', dateTime: '2026-06-18T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio BC Place Vancouver' },
  { id: 'wc28', homeTeam: 'México', awayTeam: 'República de Corea', group: 'Grupo A', dateTime: '2026-06-19T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Guadalajara' },
  // Viernes, 19 de junio 2026
  { id: 'wc29', homeTeam: 'Estados Unidos', awayTeam: 'Australia', group: 'Grupo D', dateTime: '2026-06-19T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Seattle' },
  { id: 'wc30', homeTeam: 'Escocia', awayTeam: 'Marruecos', group: 'Grupo C', dateTime: '2026-06-19T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Boston' },
  { id: 'wc31', homeTeam: 'Brasil', awayTeam: 'Haití', group: 'Grupo C', dateTime: '2026-06-20T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Filadelfia' },
  { id: 'wc32', homeTeam: 'Turquía', awayTeam: 'Paraguay', group: 'Grupo D', dateTime: '2026-06-20T04:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Bahía de San Francisco' },
  // Sábado, 20 de junio 2026
  { id: 'wc33', homeTeam: 'Países Bajos', awayTeam: 'Suecia', group: 'Grupo F', dateTime: '2026-06-20T17:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Houston' },
  { id: 'wc34', homeTeam: 'Alemania', awayTeam: 'Costa de Marfil', group: 'Grupo E', dateTime: '2026-06-20T20:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Toronto' },
  { id: 'wc35', homeTeam: 'Ecuador', awayTeam: 'Curazao', group: 'Grupo E', dateTime: '2026-06-21T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Kansas City' },
  { id: 'wc36', homeTeam: 'Túnez', awayTeam: 'Japón', group: 'Grupo F', dateTime: '2026-06-21T04:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Monterrey' },
  // Domingo, 21 de junio 2026
  { id: 'wc37', homeTeam: 'España', awayTeam: 'Arabia Saudí', group: 'Grupo H', dateTime: '2026-06-21T16:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },
  { id: 'wc38', homeTeam: 'Bélgica', awayTeam: 'RI de Irán', group: 'Grupo G', dateTime: '2026-06-21T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  { id: 'wc39', homeTeam: 'Uruguay', awayTeam: 'Cabo Verde', group: 'Grupo H', dateTime: '2026-06-21T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Miami' },
  { id: 'wc40', homeTeam: 'Nueva Zelanda', awayTeam: 'Egipto', group: 'Grupo G', dateTime: '2026-06-22T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio BC Place Vancouver' },
  // Lunes, 22 de junio 2026
  { id: 'wc41', homeTeam: 'Argentina', awayTeam: 'Austria', group: 'Grupo J', dateTime: '2026-06-22T17:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },
  { id: 'wc42', homeTeam: 'Francia', awayTeam: 'Irak', group: 'Grupo I', dateTime: '2026-06-22T21:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Filadelfia' },
  { id: 'wc43', homeTeam: 'Noruega', awayTeam: 'Senegal', group: 'Grupo I', dateTime: '2026-06-23T00:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' },
  { id: 'wc44', homeTeam: 'Jordania', awayTeam: 'Argelia', group: 'Grupo J', dateTime: '2026-06-23T03:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Bahía de San Francisco Bay' },
  // Martes, 23 de junio 2026
  { id: 'wc45', homeTeam: 'Portugal', awayTeam: 'Uzbekistán', group: 'Grupo K', dateTime: '2026-06-23T17:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Houston' },
  { id: 'wc46', homeTeam: 'Inglaterra', awayTeam: 'Ghana', group: 'Grupo L', dateTime: '2026-06-23T20:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Boston' },
  { id: 'wc47', homeTeam: 'Panamá', awayTeam: 'Croacia', group: 'Grupo L', dateTime: '2026-06-23T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Toronto' },
  { id: 'wc48', homeTeam: 'Colombia', awayTeam: 'RD Congo', group: 'Grupo K', dateTime: '2026-06-24T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Guadalajara' },
  // Miércoles, 24 de junio 2026
  { id: 'wc49', homeTeam: 'Suiza', awayTeam: 'Canadá', group: 'Grupo B', dateTime: '2026-06-24T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio BC Place Vancouver' },
  { id: 'wc50', homeTeam: 'Bosnia y Herzegovina', awayTeam: 'Catar', group: 'Grupo B', dateTime: '2026-06-24T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Seattle' },
  { id: 'wc51', homeTeam: 'Escocia', awayTeam: 'Brasil', group: 'Grupo C', dateTime: '2026-06-24T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Miami' },
  { id: 'wc52', homeTeam: 'Marruecos', awayTeam: 'Haití', group: 'Grupo C', dateTime: '2026-06-24T22:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },
  { id: 'wc53', homeTeam: 'República Checa', awayTeam: 'México', group: 'Grupo A', dateTime: '2026-06-25T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Ciudad de México' },
  { id: 'wc54', homeTeam: 'Sudáfrica', awayTeam: 'República de Corea', group: 'Grupo A', dateTime: '2026-06-25T01:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Monterrey' },
  // Jueves, 25 de junio 2026
  { id: 'wc55', homeTeam: 'Curazao', awayTeam: 'Costa de Marfil', group: 'Grupo E', dateTime: '2026-06-25T20:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Filadelfia' },
  { id: 'wc56', homeTeam: 'Ecuador', awayTeam: 'Alemania', group: 'Grupo E', dateTime: '2026-06-25T20:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' },
  { id: 'wc57', homeTeam: 'Japón', awayTeam: 'Suecia', group: 'Grupo F', dateTime: '2026-06-25T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },
  { id: 'wc58', homeTeam: 'Túnez', awayTeam: 'Países Bajos', group: 'Grupo F', dateTime: '2026-06-25T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Kansas City' },
  { id: 'wc59', homeTeam: 'Turquía', awayTeam: 'Estados Unidos', group: 'Grupo D', dateTime: '2026-06-26T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  { id: 'wc60', homeTeam: 'Paraguay', awayTeam: 'Australia', group: 'Grupo D', dateTime: '2026-06-26T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Bahía de San Francisco' },
  // Viernes, 26 de junio 2026
  { id: 'wc61', homeTeam: 'Noruega', awayTeam: 'Francia', group: 'Grupo I', dateTime: '2026-06-26T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Boston' },
  { id: 'wc62', homeTeam: 'Senegal', awayTeam: 'Irak', group: 'Grupo I', dateTime: '2026-06-26T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Toronto' },
  { id: 'wc63', homeTeam: 'Cabo Verde', awayTeam: 'Arabia Saudí', group: 'Grupo H', dateTime: '2026-06-27T00:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Houston' },
  { id: 'wc64', homeTeam: 'Uruguay', awayTeam: 'España', group: 'Grupo H', dateTime: '2026-06-27T00:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Guadalajara' },
  { id: 'wc65', homeTeam: 'Egipto', awayTeam: 'RI de Irán', group: 'Grupo G', dateTime: '2026-06-27T03:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Seattle' },
  { id: 'wc66', homeTeam: 'Nueva Zelanda', awayTeam: 'Bélgica', group: 'Grupo G', dateTime: '2026-06-27T03:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio BC Place Vancouver' },
  // Sábado, 27 de junio 2026
  { id: 'wc67', homeTeam: 'Panamá', awayTeam: 'Inglaterra', group: 'Grupo L', dateTime: '2026-06-27T21:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' },
  { id: 'wc68', homeTeam: 'Croacia', awayTeam: 'Ghana', group: 'Grupo L', dateTime: '2026-06-27T21:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Filadelfia' },
  { id: 'wc69', homeTeam: 'Colombia', awayTeam: 'Portugal', group: 'Grupo K', dateTime: '2026-06-27T23:30:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Miami' },
  { id: 'wc70', homeTeam: 'RD Congo', awayTeam: 'Uzbekistán', group: 'Grupo K', dateTime: '2026-06-27T23:30:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },
  { id: 'wc71', homeTeam: 'Argelia', awayTeam: 'Austria', group: 'Grupo J', dateTime: '2026-06-28T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Kansas City' },
  { id: 'wc72', homeTeam: 'Jordania', awayTeam: 'Argentina', group: 'Grupo J', dateTime: '2026-06-28T02:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },

  // --- DIECOISEISAVOS ---
  { id: 'wc73', homeTeam: '2º Grupo A', awayTeam: '2º Grupo B', group: 'Dieciseisavos de final', dateTime: '2026-06-28T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  { id: 'wc74', homeTeam: '1º Grupo E', awayTeam: '3º Grupo A/B/C/D/F', group: 'Dieciseisavos de final', dateTime: '2026-06-29T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Boston' },
  { id: 'wc75', homeTeam: '1º Grupo F', awayTeam: '2º Grupo C', group: 'Dieciseisavos de final', dateTime: '2026-06-29T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Monterrey' },
  { id: 'wc76', homeTeam: '1º Grupo C', awayTeam: '2º Grupo F', group: 'Dieciseisavos de final', dateTime: '2026-06-29T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Houston' },
  { id: 'wc77', homeTeam: '1º Grupo I', awayTeam: '3º Grupo C/D/F/G/H', group: 'Dieciseisavos de final', dateTime: '2026-06-30T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' },
  { id: 'wc78', homeTeam: '2º Grupo E', awayTeam: '2º Grupo I', group: 'Dieciseisavos de final', dateTime: '2026-06-30T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },
  { id: 'wc79', homeTeam: '1º Grupo A', awayTeam: '3º Grupo C/E/F/H/I', group: 'Dieciseisavos de final', dateTime: '2026-06-30T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Ciudad de México' },
  { id: 'wc80', homeTeam: '1º Grupo L', awayTeam: '3º Grupo E/H/I/J/K', group: 'Dieciseisavos de final', dateTime: '2026-07-01T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },
  { id: 'wc81', homeTeam: '1º Grupo D', awayTeam: '3º Grupo B/E/F/I/J', group: 'Dieciseisavos de final', dateTime: '2026-07-01T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Bahía de San Francisco' },
  { id: 'wc82', homeTeam: '1º Grupo G', awayTeam: '3º Grupo A/E/H/I/J', group: 'Dieciseisavos de final', dateTime: '2026-07-01T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Seattle' },
  { id: 'wc83', homeTeam: '2º Grupo K', awayTeam: '2º Grupo L', group: 'Dieciseisavos de final', dateTime: '2026-07-02T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Toronto' },
  { id: 'wc84', homeTeam: '1º Grupo H', awayTeam: '2º Grupo J', group: 'Dieciseisavos de final', dateTime: '2026-07-02T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  { id: 'wc85', homeTeam: '1º Grupo B', awayTeam: '3º Grupo E/F/G/I/J', group: 'Dieciseisavos de final', dateTime: '2026-07-02T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio BC Place Vancouver' },
  { id: 'wc86', homeTeam: '1º Grupo J', awayTeam: '2º Grupo H', group: 'Dieciseisavos de final', dateTime: '2026-07-03T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Miami' },
  { id: 'wc87', homeTeam: '1º Grupo K', awayTeam: '3º Grupo D/E/I/J/L', group: 'Dieciseisavos de final', dateTime: '2026-07-03T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Kansas City' },
  { id: 'wc88', homeTeam: '2º Grupo D', awayTeam: '2º Grupo G', group: 'Dieciseisavos de final', dateTime: '2026-07-03T23:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },

  // --- OCTAVOS ---
  { id: 'wc89', homeTeam: 'Ganador Partido 74', awayTeam: 'Ganador Partido 77', group: 'Octavos de final', dateTime: '2026-07-04T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Filadelfia' },
  { id: 'wc90', homeTeam: 'Ganador Partido 73', awayTeam: 'Ganador Partido 75', group: 'Octavos de final', dateTime: '2026-07-04T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Houston' },
  { id: 'wc91', homeTeam: 'Ganador Partido 76', awayTeam: 'Ganador Partido 78', group: 'Octavos de final', dateTime: '2026-07-05T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' },
  { id: 'wc92', homeTeam: 'Ganador Partido 79', awayTeam: 'Ganador Partido 80', group: 'Octavos de final', dateTime: '2026-07-05T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Ciudad de México' },
  { id: 'wc93', homeTeam: 'Ganador Partido 83', awayTeam: 'Ganador Partido 84', group: 'Octavos de final', dateTime: '2026-07-06T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },
  { id: 'wc94', homeTeam: 'Ganador Partido 81', awayTeam: 'Ganador Partido 82', group: 'Octavos de final', dateTime: '2026-07-06T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Seattle' },
  { id: 'wc95', homeTeam: 'Ganador Partido 86', awayTeam: 'Ganador Partido 88', group: 'Octavos de final', dateTime: '2026-07-07T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },
  { id: 'wc96', homeTeam: 'Ganador Partido 85', awayTeam: 'Ganador Partido 87', group: 'Octavos de final', dateTime: '2026-07-07T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio BC Place Vancouver' },

  // --- CUARTOS ---
  { id: 'wc97', homeTeam: 'Ganador Partido 89', awayTeam: 'Ganador Partido 90', group: 'Cuartos de final', dateTime: '2026-07-09T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Boston' },
  { id: 'wc98', homeTeam: 'Ganador Partido 93', awayTeam: 'Ganador Partido 94', group: 'Cuartos de final', dateTime: '2026-07-10T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Los Ángeles' },
  { id: 'wc99', homeTeam: 'Ganador Partido 91', awayTeam: 'Ganador Partido 92', group: 'Cuartos de final', dateTime: '2026-07-11T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Miami' },
  { id: 'wc100', homeTeam: 'Ganador Partido 95', awayTeam: 'Ganador Partido 96', group: 'Cuartos de final', dateTime: '2026-07-11T19:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Kansas City' },

  // --- SEMIS ---
  { id: 'wc101', homeTeam: 'Ganador Partido 97', awayTeam: 'Ganador Partido 98', group: 'Semifinales', dateTime: '2026-07-14T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Dallas' },
  { id: 'wc102', homeTeam: 'Ganador Partido 99', awayTeam: 'Ganador Partido 100', group: 'Semifinales', dateTime: '2026-07-15T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Atlanta' },

  // --- TERCER PUESTO ---
  { id: 'wc103', homeTeam: 'Perdedor Partido 101', awayTeam: 'Perdedor Partido 102', group: 'Tercer puesto', dateTime: '2026-07-18T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Miami' },

  // --- FINAL ---
  { id: 'wc104', homeTeam: 'Ganador Partido 101', awayTeam: 'Ganador Partido 102', group: 'Final', dateTime: '2026-07-19T15:00:00Z', homeScore: -1, awayScore: -1, status: 'scheduled', stadium: 'Estadio Nueva York Nueva Jersey' }
];

export const TEAM_FLAGS: { [key: string]: string } = {
  'México': '🇲🇽',
  'Sudáfrica': '🇿🇦',
  'República de Corea': '🇰🇷',
  'República Checa': '🇨🇿',
  'Canadá': '🇨🇦',
  'Bosnia y Herzegovina': '🇧🇦',
  'Estados Unidos': '🇺🇸',
  'Paraguay': '🇵🇾',
  'Catar': '🇶🇦',
  'Suiza': '🇨🇭',
  'Brasil': '🇧🇷',
  'Marruecos': '🇲🇦',
  'Haití': '🇭🇹',
  'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Australia': '🇦🇺',
  'Turquía': '🇹🇷',
  'Alemania': '🇩🇪',
  'Curazao': '🇨🇼',
  'Países Bajos': '🇳🇱',
  'Japón': '🇯🇵',
  'Costa de Marfil': '🇨🇮',
  'Ecuador': '🇪🇨',
  'Suecia': '🇸🇪',
  'Túnez': '🇹🇳',
  'España': '🇪🇸',
  'Cabo Verde': '🇨🇻',
  'Bélgica': '🇧🇪',
  'Egipto': '🇪🇬',
  'Arabia Saudí': '🇸🇦',
  'Uruguay': '🇺🇾',
  'RI de Irán': '🇮🇷',
  'Nueva Zelanda': '🇳🇿',
  'Francia': '🇫🇷',
  'Senegal': '🇸🇳',
  'Irak': '🇮🇶',
  'Noruega': '🇳🇴',
  'Argentina': '🇦🇷',
  'Argelia': '🇩🇿',
  'Austria': '🇦🇹',
  'Jordania': '🇯🇴',
  'Portugal': '🇵🇹',
  'RD Congo': '🇨🇩',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Croacia': '🇭🇷',
  'Ghana': '🇬🇭',
  'Panamá': '🇵🇦',
  'Uzbekistán': '🇺🇿',
  'Colombia': '🇨🇴'
};

export const TEAM_COLORS: { [key: string]: string } = {
  'México': 'bg-green-700',
  'Sudáfrica': 'bg-yellow-600',
  'República de Corea': 'bg-red-650',
  'República Checa': 'bg-blue-700',
  'Canadá': 'bg-red-600',
  'Bosnia y Herzegovina': 'bg-blue-800',
  'Estados Unidos': 'bg-blue-600',
  'Paraguay': 'bg-red-700',
  'Catar': 'bg-rose-900',
  'Suiza': 'bg-red-600',
  'Brasil': 'bg-yellow-400',
  'Marruecos': 'bg-emerald-700',
  'Haití': 'bg-blue-700',
  'Escocia': 'bg-blue-900',
  'Australia': 'bg-yellow-500',
  'Turquía': 'bg-red-600',
  'Alemania': 'bg-black',
  'Curazao': 'bg-sky-500',
  'Países Bajos': 'bg-orange-500',
  'Japón': 'bg-blue-900',
  'Costa de Marfil': 'bg-orange-400',
  'Ecuador': 'bg-yellow-500',
  'Suecia': 'bg-yellow-300',
  'Túnez': 'bg-red-500',
  'España': 'bg-red-600',
  'Cabo Verde': 'bg-blue-900',
  'Bélgica': 'bg-red-800',
  'Egipto': 'bg-red-750',
  'Arabia Saudí': 'bg-green-600',
  'Uruguay': 'bg-sky-400',
  'RI de Irán': 'bg-emerald-600',
  'Nueva Zelanda': 'bg-black',
  'Francia': 'bg-blue-900',
  'Senegal': 'bg-green-600',
  'Irak': 'bg-green-800',
  'Noruega': 'bg-red-700',
  'Argentina': 'bg-sky-400',
  'Argelia': 'bg-emerald-600',
  'Austria': 'bg-red-600',
  'Jordania': 'bg-red-500',
  'Portugal': 'bg-red-700',
  'RD Congo': 'bg-blue-600',
  'Inglaterra': 'bg-white',
  'Croacia': 'bg-red-600',
  'Ghana': 'bg-yellow-500',
  'Panamá': 'bg-red-650',
  'Uzbekistán': 'bg-blue-500',
  'Colombia': 'bg-yellow-400'
};
